version: '3.7'
services: 
  api:
    container_name: API
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - docker_network
    depends_on:
      - db

  db:
    container_name: BD
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      
    volumes:
      - api_db_data:/var/lib/postgresql/data
    networks:
      - docker_network
    
    


networks:
  docker_network:

volumes:
  api_db_data: