version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - docker-network

  db:
    container_name: db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'
    ports:
      - '5432:5432'
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
